# Generated by Django 5.2.4 on 2025-10-19 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name': 'программу', 'verbose_name_plural': 'программы'},
        ),
        migrations.RemoveField(
            model_name='programs',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programs',
            name='url',
        ),
        migrations.AlterField(
            model_name='programs',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Программа'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название упражения')),
                ('image', models.ImageField(blank=True, upload_to='programs/images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=100, verbose_name='Краткое описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programs', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'упражнение',
                'verbose_name_plural': 'упражнения',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_photo', models.ImageField(blank=True, upload_to='programs/images/', verbose_name='Фото')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.exercise', verbose_name='Упражнения')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
    ]
