# Generated by Django 5.2.4 on 2025-10-19 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_programs_options_remove_programs_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='title',
        ),
    ]
